import type { Metadata } from "next";
import { Livvic } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";
import { Toaster } from "@/components/ui/sonner";
import { Progress } from "@/components/ui/progress";
import AppProgress from "@/components/app-progress";

const livvic = Livvic({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "myteam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={livvic.className}>
        <div className="relative">
          <AppProgress />
          <Navigation />
          {children}
          <Footer />
        </div>
        <Toaster />
      </body>
    </html>
  );
}
